In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "02-Homework_04-Pandas_Instructions_HeroesOfPymoli_Resources_purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
df = pd.read_csv(file_to_load)

In [2]:
df.head(6)

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61

In [3]:
df.nunique()

Purchase ID    780
SN             576
Age             39
Gender           3
Item ID        183
Item Name      179
Price          145
dtype: int64

In [4]:
# players 
#Total=len(df['SN'].unique())
#Total

Total={'Number of players':len(df['SN'].unique())}
df1 = pd.DataFrame((Total), index=[0])
df1

   Number of players
0                576

In [5]:
#Average Price 
avg_price=(df['Price'].mean())

In [6]:
#Number of unique items
unique_items=len(df['Item ID'].unique())

In [7]:
#Number of Purchases
num_purchases=len(df['Purchase ID'].unique())

In [8]:
#Toral Revenue
#Average Price 
total_revenue=(df['Price'].sum())

In [9]:
final_purchase_analysys = pd.DataFrame({"Number of Unique Items":[unique_items],
                           "Average Price":[avg_price], 
                           "Number of Purchases": [num_purchases], 
                           "Total Revenue": [total_revenue]})
final_purchase_analysys.style.format({'Average Price':"${:,.2f}",
                         'Total Revenue': '${:,.2f}'})

In [10]:
#Number of male
male = df.loc[df["Gender"] == "Male"]
(male['Gender'])
male=len(male['SN'].unique())
male

484

In [11]:
#Number of female
female = df.loc[df["Gender"] == "Female"]
(female['Gender'])
female=len(female['SN'].unique())
female

81

In [12]:
#Number of other gender
other = df.loc[df["Gender"] == "Other / Non-Disclosed"]
(other['Gender'])
other=len(other['SN'].unique())
other

11

In [13]:
total_sex=male+female+other
total_sex

576

In [14]:
#percentage male
(male/total_sex)*100

84.02777777777779

In [15]:
#percentage female
(female/total_sex)*100

14.0625

In [16]:
#percentage other
(other/total_sex)*100

1.9097222222222223

In [17]:
bygender=df.groupby("Gender")

In [18]:
countgender=bygender.nunique()["SN"]

In [19]:
percentage_players= ((countgender) / (total_sex)) *100

In [20]:
Dender_demo_final = pd.DataFrame({"Percentage of Players": percentage_players, 
                                    "Total Count": countgender})
Dender_demo_final.sort_values(["Total Count"], ascending = False).style.format({"Percentage of Players":"{:.2f}"})

In [21]:
#Purchase count male
male = df.loc[df["Gender"] == "Male"]
len(male['Gender'])

652

In [22]:
#Purchase count female
female = df.loc[df["Gender"] == "Female"]
len(female['Gender'])

113

In [23]:
#Purchase count other
other = df.loc[df["Gender"] == "Other / Non-Disclosed"]
len(other['Gender'])

15

In [24]:
#Average Purchase Price male
male = df.loc[df["Gender"] == "Male"]
(male["Price"]).sum()/len(male['Gender'])

3.0178527607361967

In [25]:
#Average Purchase Price female
female = df.loc[df["Gender"] == "Female"]
(female["Price"]).sum()/len(female['Gender'])

3.203008849557522

In [26]:
#Average Purchase Price other
other = df.loc[df["Gender"] == "Other / Non-Disclosed"]
(other["Price"]).sum()/len(other['Gender'])

3.3459999999999996

In [27]:
#Total purchase value male
male = df.loc[df["Gender"] == "Male"]
(male["Price"]).sum()

1967.64

In [28]:
#Total purchase value female
female = df.loc[df["Gender"] == "Female"]
(female["Price"]).sum()

361.94

In [29]:
#Total purchase value other
other = df.loc[df["Gender"] == "Other / Non-Disclosed"]
(other["Price"]).sum()

50.19

In [30]:
#Avg Total Purchase per Person Male 
(male["Price"]).sum()/len(male['SN'].unique())

4.065371900826446

In [31]:
#Avg Total Purchase per Person Female 
(female["Price"]).sum()/len(female['SN'].unique())

4.468395061728395

In [32]:
#Avg Total Purchase per Person Other 
(other["Price"]).sum()/len(other['SN'].unique())

4.5627272727272725

In [33]:
gender_stats=df.groupby("Gender")

In [34]:
purchase_count = gender_stats["Purchase ID"].count()

In [35]:
avg_purchase_price = gender_stats["Price"].mean()

In [36]:
avg_purchase_total = gender_stats["Price"].sum()

In [37]:
avg_purchase_per_person = avg_purchase_total/gender_stats.nunique()["SN"]

In [38]:
gender_demographics = pd.DataFrame({"Purchase Count": purchase_count, 
                                    "Average Purchase Price": avg_purchase_price,
                                    "Average Purchase Value":avg_purchase_total,
                                    "Avg Purchase Total per Person": avg_purchase_per_person})
gender_demographics.style.format({"Average Purchase Value":"${:,.2f}",
                                  "Average Purchase Price":"${:,.2f}",
                                  "Avg Purchase Total per Person":"${:,.2f}"})

In [66]:
# Bins of ages
age_bins = [0, 9.90, 19.90, 24.90, 29.90, 34.90, 39.90, 99999]
group_names = ["<10","15-19", "20-24", "25-29", "30-34", "35-39", "40+"]

In [67]:
# sort age values into bins 
df["Age Group"] = pd.cut(df["Age"],age_bins, labels=group_names)
df

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Group
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67,20-24
8,8,Undjask33,22,Male,21,Souleater,1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,35-39
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,35-39
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,2.52,20-24
17,17,Zontibe81,21,Male,161,Devine,1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64,30-34
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60,20-24
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48,20-24
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,3.40,40+
24,24,Siala43,30,Male,141,Persuasion,3.19,30-34
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,1.61,15-19
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09,<10
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,20-24
...,...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36,15-19
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,35-39
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05,20-24
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15,15-19
756,756,Ilast79,20,Male,73,Ritual Mace,2.05,20-24
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
758,758,Iral74,21,Male,182,Toothpick,4.03,20-24
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77,25-29
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38,20-24
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70,40+
762,762,Asur53,26,Male,110,Suspension,1.44,25-29
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75,20-24
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07,15-19
765,765,Irith83,18,Male,130,Alpha,2.07,15-19
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24
767,767,Ilmol66,8,Female,92,Final Critic,4.88,<10
768,768,Assassasta79,38,Male,92,Final Critic,4.88,35-39
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58,15-19
770,770,Lirtosia63,34,Male,12,Dawne,1.02,30-34
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35,15-19
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58,25-29
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,4.19,15-19
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24
778,778,Sisur91,7,Male,101,Final Critic,4.19,<10
779,779,Ennrian78,24,Male,50,Dawn,4.60,20-24

In [68]:
#group age
age_grouped = df.groupby("Age Group")
age_grouped

In [69]:
count_age = age_grouped["SN"].nunique()
count_age

Age Group
<10       17
15-19    129
20-24    258
25-29     77
30-34     52
35-39     31
40+       12
Name: SN, dtype: int64

In [70]:

Totals=len(df['SN'].unique())
percentage_by_age=(count_age/Totals)*100

In [71]:
age_demographics = pd.DataFrame({"Total Count": count_age ,"Percentage of Players" :percentage_by_age})
age_demographics

           Total Count  Percentage of Players
Age Group
<10                 17               2.951389
15-19              129              22.395833
20-24              258              44.791667
25-29               77              13.368056
30-34               52               9.027778
35-39               31               5.381944
40+                 12               2.083333

In [45]:
purchase_count_age = age_grouped["Purchase ID"].count()

In [46]:
avg_purchase_price_age = age_grouped["Price"].mean()

In [47]:
total_purchase_value = age_grouped["Price"].sum()

In [48]:
avg_purchase_per_person_age = total_purchase_value/count_age

In [49]:
age_demo2 = pd.DataFrame({"Purchase Count": purchase_count_age,
                                 "Average Purchase Price": avg_purchase_price_age,
                                 "Total Purchase Value":total_purchase_value,
                                 "Average Purchase Total per Person": avg_purchase_per_person_age})
age_demo2.style.format({"Average Purchase Price":"${:,.2f}",
                               "Total Purchase Value":"${:,.2f}",
                               "Average Purchase Total per Person":"${:,.2f}"})

In [50]:
spender= df.groupby("SN")
spender

In [51]:
count_spender= spender["Purchase ID"].count()

In [52]:
avg_price_spender= spender["Price"].mean()

In [53]:
purchase_total= spender["Price"].sum()

In [54]:
top_spenders = pd.DataFrame({"Purchase Count": count_spender,
                             "Average Purchase Price": avg_price_spender,
                             "Total Purchase Value":purchase_total})

In [55]:
final_spender=top_spenders.sort_values(["Total Purchase Value"], ascending=False).head()
final_spender.style.format({"Average Purchase Total":"${:,.2f}",
                                 "Average Purchase Price":"${:,.2f}", 
                                 "Total Purchase Value":"${:,.2f}"})

In [56]:
items = df[["Item ID", "Item Name", "Price"]]

In [57]:
item_stats = items.groupby(["Item ID","Item Name"])

In [58]:
count_item = item_stats["Price"].count()

In [59]:
purchase_value = (item_stats["Price"].sum())

In [60]:
item_price = purchase_value/count_item

In [61]:
popular_items = pd.DataFrame({"Purchase Count": count_item, 
                                   "Item Price": item_price,
                                   "Total Purchase Value":purchase_value})

In [62]:
popular_items_final=popular_items.sort_values(["Purchase Count"], ascending=False).head()
popular_items_final.style.format({"Item Price":"${:,.2f}",
                                "Total Purchase Value":"${:,.2f}"})

In [63]:
popular_items.sort_values(["Total Purchase Value"],ascending=False).head()

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
82,Nirvana,9,4.90,44.10
145,Fiery Glass Crusader,9,4.58,41.22
92,Final Critic,8,4.88,39.04
103,Singed Scalpel,8,4.35,34.80

In [65]:
popular_items.style.format({"Item Price":"${:,.2f}",
                                "Total Purchase Value":"${:,.2f}"})